### ISSUE TITLE
Build failed on Debian Bullseye

### ISSUE THREAD

**Issue by donihalim** [torrinfail/dwmblocks#22]
Hi, i got this error when running `make` on debian bullseye(testing)

```
cc `pkg-config --cflags x11` `pkg-config --libs x11` dwmblocks.c -o dwmblocks
/usr/bin/ld: /tmp/cchx5S7i.o: in function `setroot':
dwmblocks.c:(.text+0x39e): undefined reference to `XOpenDisplay'
/usr/bin/ld: dwmblocks.c:(.text+0x410): undefined reference to `XStoreName'
/usr/bin/ld: dwmblocks.c:(.text+0x41f): undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: output] Error 1
```

**Comment by beardedone55** [comment]
I get the same error with gcc.  The problem is with the order of the parameters that are passed to cc.  The linker needs the library parameter (-l) to come after the object file.  In this case, the compiler and linker are called with one call to cc, so the library parameters must come after the source filename. The library parameters are created by the call to `pkg-config --libs x11`. If Makefile is modified so it calls cc as follows, it will fix the problem:

```cc `pkg-config --cflags x11` dwmblocks.c `pkg-config --libs x11` -o dwmblocks```

This was broken by commit 3906995607d60e2721a03db78d4f3f4b63cd6afb.

**Comment by beardedone55** [comment]
It looks like there is a pull request to fix this:  #17

**Comment by donihalim** [comment]
> It looks like there is a pull request to fix this: #17

Solved, using this. Thank you
